# Generated by Django 2.0 on 2020-07-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClickNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'click_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('url', models.CharField(blank=True, max_length=60, null=True)),
                ('open_id', models.CharField(blank=True, max_length=28, null=True)),
                ('nickname', models.CharField(blank=True, max_length=60, null=True)),
                ('avatar', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.CharField(blank=True, max_length=400, null=True)),
                ('comment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('like_count', models.SmallIntegerField(blank=True, null=True)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cur', models.DateTimeField(blank=True, null=True)),
                ('verify', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(blank=True, max_length=50, null=True)),
                ('comment_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'comment_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DongqiudiJijin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('thumb', models.CharField(blank=True, max_length=255, null=True)),
                ('mp4', models.CharField(blank=True, max_length=255, null=True)),
                ('pub_time', models.DateTimeField(blank=True, null=True)),
                ('shoucang', models.SmallIntegerField(blank=True, null=True)),
                ('like', models.SmallIntegerField(blank=True, null=True)),
                ('fenxiang', models.SmallIntegerField(blank=True, null=True)),
                ('dianji', models.SmallIntegerField(blank=True, null=True)),
                ('han', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dongqiudi_jijin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DongqiudiVidio',
            fields=[
                ('id', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('thumb', models.CharField(max_length=255)),
                ('mp4', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_time', models.DateTimeField(blank=True, null=True)),
                ('shoucang', models.SmallIntegerField(blank=True, null=True)),
                ('like', models.SmallIntegerField(blank=True, null=True)),
                ('fenxiang', models.SmallIntegerField(blank=True, null=True)),
                ('dianji', models.SmallIntegerField(blank=True, null=True)),
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dongqiudi_vidio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=15, null=True)),
                ('team_a', models.CharField(blank=True, max_length=40, null=True)),
                ('team_a_logo', models.CharField(blank=True, max_length=90, null=True)),
                ('team_b', models.CharField(blank=True, max_length=40, null=True)),
                ('team_b_logo', models.CharField(blank=True, max_length=90, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game_match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomeInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.SmallIntegerField(blank=True, null=True)),
                ('day_user', models.SmallIntegerField(blank=True, null=True)),
                ('wechat', models.CharField(blank=True, max_length=11, null=True)),
                ('show', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'home_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jieshao',
            fields=[
                ('yingchao', models.CharField(blank=True, max_length=255, null=True)),
                ('xijia', models.CharField(blank=True, max_length=255, null=True)),
                ('yijia', models.CharField(blank=True, max_length=255, null=True)),
                ('dejia', models.CharField(blank=True, max_length=255, null=True)),
                ('fajia', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'jieshao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsPriase',
            fields=[
                ('url', models.CharField(blank=True, max_length=55, null=True)),
                ('open_id', models.CharField(blank=True, max_length=28, null=True)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('avatar', models.CharField(blank=True, max_length=150, null=True)),
                ('pub_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_priase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NurIndex',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_time', models.DateTimeField(blank=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nur_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NurNews',
            fields=[
                ('url', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('p_0', models.CharField(blank=True, db_column='P_0', max_length=1000, null=True)),
                ('p_1', models.CharField(blank=True, max_length=1500, null=True)),
                ('p_2', models.TextField(blank=True, null=True)),
                ('p_3', models.TextField(blank=True, null=True)),
                ('p_4', models.TextField(blank=True, null=True)),
                ('p_5', models.TextField(blank=True, null=True)),
                ('p_6', models.TextField(blank=True, null=True)),
                ('p_7', models.TextField(blank=True, null=True)),
                ('p_8', models.TextField(blank=True, null=True)),
                ('p_9', models.TextField(blank=True, db_column='P_9', null=True)),
                ('p_10', models.TextField(blank=True, db_column='P_10', null=True)),
                ('p_11', models.TextField(blank=True, db_column='P_11', null=True)),
                ('p_12', models.TextField(blank=True, db_column='P_12', null=True)),
                ('p_13', models.TextField(blank=True, db_column='P_13', null=True)),
                ('p_14', models.TextField(blank=True, db_column='P_14', null=True)),
                ('p_15', models.TextField(blank=True, db_column='P_15', null=True)),
                ('p_16', models.TextField(blank=True, db_column='P_16', null=True)),
                ('p_17', models.TextField(blank=True, db_column='P_17', null=True)),
                ('p_18', models.TextField(blank=True, db_column='P_18', null=True)),
                ('p_19', models.TextField(blank=True, db_column='P_19', null=True)),
                ('p_20', models.TextField(blank=True, db_column='P_20', null=True)),
                ('p_21', models.TextField(blank=True, db_column='P_21', null=True)),
                ('p_22', models.TextField(blank=True, db_column='P_22', null=True)),
                ('p_23', models.TextField(blank=True, db_column='P_23', null=True)),
                ('p_24', models.TextField(blank=True, db_column='P_24', null=True)),
                ('p_25', models.TextField(blank=True, db_column='P_25', null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('root', models.CharField(blank=True, max_length=40, null=True)),
                ('pub_time', models.DateTimeField(blank=True, null=True)),
                ('a', models.CharField(blank=True, max_length=100, null=True)),
                ('b', models.CharField(blank=True, max_length=100, null=True)),
                ('c', models.CharField(blank=True, max_length=100, null=True)),
                ('d', models.CharField(blank=True, max_length=100, null=True)),
                ('e', models.CharField(blank=True, max_length=100, null=True)),
                ('p', models.CharField(blank=True, max_length=40, null=True)),
                ('span', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nur_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NurSlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=128, null=True)),
                ('text', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nur_slide_show',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leage', models.CharField(blank=True, max_length=50, null=True)),
                ('be_from', models.CharField(blank=True, max_length=50, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_paly', models.DateTimeField(blank=True, null=True)),
                ('round_name', models.CharField(blank=True, max_length=30, null=True)),
                ('team_a_name', models.CharField(blank=True, db_column='team_A_name', max_length=30, null=True)),
                ('team_a_logo', models.CharField(blank=True, db_column='team_A_logo', max_length=100, null=True)),
                ('team_b_name', models.CharField(blank=True, db_column='team_B_name', max_length=30, null=True)),
                ('team_b_logo', models.CharField(blank=True, db_column='team_B_logo', max_length=100, null=True)),
                ('fs_a', models.CharField(blank=True, db_column='fs_A', max_length=3, null=True)),
                ('fs_b', models.CharField(blank=True, db_column='fs_B', max_length=3, null=True)),
                ('match_title', models.CharField(blank=True, max_length=60, null=True)),
                ('date_utc', models.CharField(blank=True, max_length=12, null=True)),
                ('time_utc', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leage', models.CharField(blank=True, max_length=30, null=True)),
                ('ranking', models.SmallIntegerField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=30, null=True)),
                ('matches_won', models.CharField(blank=True, max_length=4, null=True)),
                ('matches_drew', models.CharField(blank=True, max_length=4, null=True)),
                ('matches_win', models.CharField(blank=True, max_length=4, null=True)),
                ('matches', models.CharField(blank=True, max_length=5, null=True)),
                ('score', models.CharField(blank=True, max_length=4, null=True)),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('goal', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shoucang',
            fields=[
                ('open_id', models.CharField(max_length=28)),
                ('url', models.CharField(blank=True, max_length=155, null=True)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'shoucang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leage', models.CharField(blank=True, max_length=30, null=True)),
                ('be_from', models.CharField(blank=True, max_length=30, null=True)),
                ('team', models.CharField(blank=True, max_length=30, null=True)),
                ('ranking', models.SmallIntegerField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=150, null=True)),
                ('count', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=28)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.SmallIntegerField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VidioUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(blank=True, max_length=28, null=True)),
                ('vidio_url', models.CharField(blank=True, max_length=100, null=True)),
                ('like', models.SmallIntegerField(blank=True, null=True)),
                ('shoucang', models.SmallIntegerField(blank=True, null=True)),
                ('fanxiang', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vidio_user',
                'managed': False,
            },
        ),
    ]
